baseURL = "/"
languageCode = "en-us"
title = "Blockchain NZ"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Blockchain NZ"

  [params.homepage_meta_tags]
    meta_description = "Blockchain NZ aims to onboard individuals with fundamental blockchain technologies and their applications. We hope that everyone will find enjoyment in embracing this transformative technology and exploring new horizons."
    meta_og_title = "Blockchain NZ"
    meta_og_type = "website"
    meta_og_url = "https://blockchain.nz"
    meta_og_image = "https://s3.ap-southeast-2.amazonaws.com/www.blockchain.nz/images/HomePage.png"
    meta_og_description = "Blockchain NZ aims to onboard individuals with fundamental blockchain technologies and their applications. We hope that everyone will find enjoyment in embracing this transformative technology and exploring new horizons."

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[permalinks]
  pages = "/:filename/"